# Generated by Django 4.2.2 on 2023-07-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'skills', 'verbose_name_plural': 'skills'},
        ),
    ]
