# Generated by Django 4.2.5 on 2023-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['is_read', '-created'], 'verbose_name': 'messages', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
