# Generated by Django 4.2.5 on 2023-09-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_messages_options_alter_messages_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
    ]
