# Generated by Django 4.2.2 on 2023-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_projects_total_vote_projects_vote_ratio_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'projects', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='projects',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/logo.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
