# Generated by Django 4.2.2 on 2023-07-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_options_projects_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='projects.tag'),
        ),
    ]
