# Generated by Django 4.2.5 on 2023-09-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projects_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-vote_ratio', '-total_vote', '-created'], 'verbose_name': 'projects', 'verbose_name_plural': 'projects'},
        ),
    ]
