# Generated by Django 4.2.5 on 2023-09-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_options'),
        ('projects', '0010_alter_projects_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
